// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use crate::GsocSerialBatchRecord;
use multiversx_sc::proxy_imports::*;

pub struct GsocRegistryProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for GsocRegistryProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = GsocRegistryProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        GsocRegistryProxyMethods { wrapped_tx: tx }
    }
}

pub struct GsocRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> GsocRegistryProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        governance: Arg0,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .argument(&governance)
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> GsocRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }

    pub fn reserve_serial<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        itmo_serial: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, bool> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("reserveSerial")
            .argument(&itmo_serial)
            .original_result()
    }

    pub fn register_serial_batch<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<u32>,
        Arg3: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg4: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg5: ProxyArg<u64>,
    >(
        self,
        itmo_serial: Arg0,
        project_id: Arg1,
        vintage_year: Arg2,
        serial_start: Arg3,
        serial_end: Arg4,
        quantity: Arg5,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("registerSerialBatch")
            .argument(&itmo_serial)
            .argument(&project_id)
            .argument(&vintage_year)
            .argument(&serial_start)
            .argument(&serial_end)
            .argument(&quantity)
            .original_result()
    }

    pub fn cancel_reservation<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        itmo_serial: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("cancelReservation")
            .argument(&itmo_serial)
            .original_result()
    }

    pub fn record_retirement<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<ManagedAddress<Env::Api>>,
        Arg3: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        itmo_serial: Arg0,
        beneficiary_name: Arg1,
        beneficiary_address: Arg2,
        burn_tx_hash: Arg3,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("recordRetirement")
            .argument(&itmo_serial)
            .argument(&beneficiary_name)
            .argument(&beneficiary_address)
            .argument(&burn_tx_hash)
            .original_result()
    }

    pub fn add_verifier<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        verifier: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("addVerifier")
            .argument(&verifier)
            .original_result()
    }

    pub fn get_serial_record<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        itmo_serial: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, OptionalValue<GsocSerialBatchRecord<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getSerialRecord")
            .argument(&itmo_serial)
            .original_result()
    }

    pub fn get_total_supply(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u64> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getTotalSupply")
            .original_result()
    }

    pub fn get_total_retired(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u64> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getTotalRetired")
            .original_result()
    }

    pub fn is_serial_retired<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        itmo_serial: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, bool> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("isSerialRetired")
            .argument(&itmo_serial)
            .original_result()
    }

    pub fn get_project_serials<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        project_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u64> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getProjectSerials")
            .argument(&project_id)
            .original_result()
    }

    pub fn is_serial_reserved<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        itmo_serial: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, bool> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("isSerialReserved")
            .argument(&itmo_serial)
            .original_result()
    }

    pub fn set_governance<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        governance: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setGovernance")
            .argument(&governance)
            .original_result()
    }

    pub fn accept_governance(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("acceptGovernance")
            .original_result()
    }

    pub fn governance(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedAddress<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getGovernance")
            .original_result()
    }

    pub fn pending_governance(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedAddress<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getPendingGovernance")
            .original_result()
    }
}
