// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           15
// Async Callback (empty):               1
// Total number of exported functions:  18

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    mrv_buffer_pool
    (
        init => init
        upgrade => upgrade
        setCarbonCreditAddr => set_carbon_credit_addr
        depositBufferCredits => deposit_buffer_credits
        cancelBufferCredits => cancel_buffer_credits
        replenishBufferCredits => replenish_buffer_credits
        getBufferRecord => get_buffer_record
        getTotalPoolBalance => get_total_pool_balance
        addAuthorizedCaller => add_authorized_caller
        removeAuthorizedCaller => remove_authorized_caller
        isAuthorizedCaller => is_authorized_caller
        getStorageVersion => storage_version
        setGovernance => set_governance
        acceptGovernance => accept_governance
        getGovernance => governance
        getPendingGovernance => pending_governance
        revokeGovernance => revoke_governance
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
