// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           19
// Async Callback (empty):               1
// Total number of exported functions:  22

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    mrv_income_distribution
    (
        init => init
        upgrade => upgrade
        setGovernanceReadAddress => set_governance_read_address
        clearGovernanceReadAddress => clear_governance_read_address
        fundDistribution => fund_distribution
        claimYield => claim_yield
        pauseDistribution => pause_distribution
        unpauseDistribution => unpause_distribution
        reclaimExpired => reclaim_expired
        recoverShortfall => recover_shortfall
        getDistribution => get_distribution
        isClaimed => is_claimed
        getClaimWindow => get_claim_window
        getGovernanceReadAddress => governance_read_address
        getDistributionEscrow => distribution_escrow
        getStorageVersion => storage_version
        setGovernance => set_governance
        acceptGovernance => accept_governance
        getGovernance => governance
        getPendingGovernance => pending_governance
        revokeGovernance => revoke_governance
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
