// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           53
// Async Callback (empty):               1
// Total number of exported functions:  56

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    mrv_carbon_credit
    (
        init => init
        upgrade => upgrade
        setGovernanceReadAddress => set_governance_read_address
        clearGovernanceReadAddress => clear_governance_read_address
        setRegistryLifecycleAddress => set_registry_lifecycle_address
        clearRegistryLifecycleAddress => clear_registry_lifecycle_address
        setDvcuTokenId => set_dvcu_token_id
        setDgscTokenId => set_dgsc_token_id
        issueCredits => issue_credits
        registerCommittedBundle => register_committed_bundle
        registerImeRecord => register_ime_record
        confirmBufferDeposit => confirm_buffer_deposit
        revokeImeRecord => revoke_ime_record
        initiateRetirement => initiate_retirement
        confirmRetirementBurn => confirm_retirement_burn
        recordIssuanceLotReversal => record_issuance_lot_reversal
        revertRetirement => revert_retirement
        issueGsocCredits => issue_gsoc_credits
        registerGsocBundle => register_gsoc_bundle
        burnAndRetireGsoc => burn_and_retire_gsoc
        addApprovedGsocVerifier => add_approved_gsoc_verifier
        removeApprovedGsocVerifier => remove_approved_gsoc_verifier
        isGsocVerifierApproved => is_gsoc_verifier_approved
        getCanonicalGsocSerialInventoryHash => get_canonical_gsoc_serial_inventory_hash
        verifyCanonicalGsocSerialInventoryHash => verify_canonical_gsoc_serial_inventory_hash
        getImeRecord => get_ime_record
        getActiveImeRecordVersion => get_active_ime_record_version
        getImeRecordVersionCount => get_ime_record_version_count
        getImeRecordVersion => get_ime_record_version
        getIssuanceImeRecordVersion => get_issuance_ime_record_version
        getRetirement => get_retirement
        getRecordedIssuanceLotReversal => get_recorded_issuance_lot_reversal
        getIssuedIssuanceLotRecipient => get_issued_issuance_lot_recipient
        getGsocSerialRecipient => get_gsoc_serial_recipient
        getDvcuTokenId => dvcu_token_id
        getDgscTokenId => dgsc_token_id
        getTotalDvcuMinted => total_dvcu_minted
        getTotalDvcuBurned => total_dvcu_burned
        getTotalDgscMinted => total_dgsc_minted
        getTotalDgscBurned => total_dgsc_burned
        getGsocProjectTotalIssued => project_gsoc_total_issued
        getGsocProjectTotalRetired => project_gsoc_total_retired
        getGsocProjectSerialCount => project_gsoc_serial_count
        getRetiredIssuanceLotAmount => retired_issuance_lot_amount
        getRegistryLifecycleAddress => registry_lifecycle_address
        getGsocSerialRemaining => gsoc_serial_remaining
        getGsocRetirementEvent => gsoc_retirement_events
        getGsocRetirementSeqCount => gsoc_retirement_seq_count
        getGovernanceReadAddress => governance_read_address
        getStorageVersion => storage_version
        setGovernance => set_governance
        acceptGovernance => accept_governance
        getGovernance => governance
        getPendingGovernance => pending_governance
        revokeGovernance => revoke_governance
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
