// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           22
// Async Callback (empty):               1
// Total number of exported functions:  25

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    mrv_carbon_credit
    (
        init => init
        upgrade => upgrade
        issueCredits => issue_credits
        registerCommittedBundle => register_committed_bundle
        registerImeRecord => register_ime_record
        confirmBufferDeposit => confirm_buffer_deposit
        revokeImeRecord => revoke_ime_record
        initiateRetirement => initiate_retirement
        confirmRetirementBurn => confirm_retirement_burn
        revertRetirement => revert_retirement
        issueGsocCredits => issue_gsoc_credits
        registerGsocBundle => register_gsoc_bundle
        burnAndRetireGsoc => burn_and_retire_gsoc
        addApprovedGsocVerifier => add_approved_gsoc_verifier
        removeApprovedGsocVerifier => remove_approved_gsoc_verifier
        isGsocVerifierApproved => is_gsoc_verifier_approved
        getImeRecord => get_ime_record
        getRetirement => get_retirement
        getStorageVersion => storage_version
        setGovernance => set_governance
        acceptGovernance => accept_governance
        getGovernance => governance
        getPendingGovernance => pending_governance
        revokeGovernance => revoke_governance
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
