// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use crate::DistributionRecord;
use multiversx_sc::proxy_imports::*;

pub struct IncomeDistributionProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for IncomeDistributionProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = IncomeDistributionProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        IncomeDistributionProxyMethods { wrapped_tx: tx }
    }
}

pub struct IncomeDistributionProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> IncomeDistributionProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
        Arg1: ProxyArg<TokenIdentifier<Env::Api>>,
    >(
        self,
        governance: Arg0,
        come_token_id: Arg1,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .argument(&governance)
            .argument(&come_token_id)
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> IncomeDistributionProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }

    pub fn fund_distribution<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<u64>,
        Arg3: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg4: ProxyArg<u64>,
    >(
        self,
        distribution_id: Arg0,
        merkle_root: Arg1,
        snapshot_block: Arg2,
        manifest_cid: Arg3,
        expiry_epoch: Arg4,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("fundDistribution")
            .argument(&distribution_id)
            .argument(&merkle_root)
            .argument(&snapshot_block)
            .argument(&manifest_cid)
            .argument(&expiry_epoch)
            .original_result()
    }

    pub fn claim_yield<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<BigUint<Env::Api>>,
        Arg2: ProxyArg<ManagedVec<Env::Api, ManagedBuffer<Env::Api>>>,
    >(
        self,
        distribution_id: Arg0,
        amount_scaled: Arg1,
        merkle_proof: Arg2,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("claimYield")
            .argument(&distribution_id)
            .argument(&amount_scaled)
            .argument(&merkle_proof)
            .original_result()
    }

    pub fn pause_distribution<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        distribution_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("pauseDistribution")
            .argument(&distribution_id)
            .original_result()
    }

    pub fn unpause_distribution<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        distribution_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("unpauseDistribution")
            .argument(&distribution_id)
            .original_result()
    }

    pub fn reclaim_expired<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        distribution_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("reclaimExpired")
            .argument(&distribution_id)
            .original_result()
    }

    pub fn recover_shortfall<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        distribution_id: Arg0,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("recoverShortfall")
            .argument(&distribution_id)
            .original_result()
    }

    pub fn get_distribution<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        distribution_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, OptionalValue<DistributionRecord<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getDistribution")
            .argument(&distribution_id)
            .original_result()
    }

    pub fn is_claimed<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        distribution_id: Arg0,
        holder: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, bool> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("isClaimed")
            .argument(&distribution_id)
            .argument(&holder)
            .original_result()
    }

    pub fn get_claim_window<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        distribution_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u64> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getClaimWindow")
            .argument(&distribution_id)
            .original_result()
    }

    pub fn get_storage_version(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u32> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getStorageVersion")
            .original_result()
    }

    pub fn set_governance<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        governance: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setGovernance")
            .argument(&governance)
            .original_result()
    }

    pub fn accept_governance(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("acceptGovernance")
            .original_result()
    }

    pub fn governance(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedAddress<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getGovernance")
            .original_result()
    }

    pub fn pending_governance(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedAddress<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getPendingGovernance")
            .original_result()
    }
}
