// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           12
// Async Callback (empty):               1
// Total number of exported functions:  15

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    mrv_reserve_proof_registry
    (
        init => init
        upgrade => upgrade
        anchorReserveProof => anchor_reserve_proof
        anchorGsocReserveProof => anchor_gsoc_reserve_proof
        getReserveProof => get_reserve_proof
        getLatestReserveProof => get_latest_reserve_proof
        getGsocReserveProof => get_gsoc_reserve_proof
        getLatestGsocReserveProof => get_latest_gsoc_reserve_proof
        getStorageVersion => storage_version
        setGovernance => set_governance
        acceptGovernance => accept_governance
        getGovernance => governance
        getPendingGovernance => pending_governance
        revokeGovernance => revoke_governance
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
