// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           22
// Async Callback (empty):               1
// Total number of exported functions:  25

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    mrv_reserve_proof_registry
    (
        init => init
        upgrade => upgrade
        setGovernanceReadAddress => set_governance_read_address
        clearGovernanceReadAddress => clear_governance_read_address
        setCarbonCreditAddr => set_carbon_credit_addr
        setBufferPoolAddr => set_buffer_pool_addr
        anchorReserveProof => anchor_reserve_proof
        anchorGsocReserveProof => anchor_gsoc_reserve_proof
        getReserveProof => get_reserve_proof
        getLatestReserveProof => get_latest_reserve_proof
        verifyHolderSnapshot => verify_holder_snapshot
        getGsocReserveProof => get_gsoc_reserve_proof
        getLatestGsocReserveProof => get_latest_gsoc_reserve_proof
        getCanonicalGsocSerialInventoryHash => get_canonical_gsoc_serial_inventory_hash_view
        verifyGsocSerialInventoryHash => verify_gsoc_serial_inventory_hash
        getCarbonCreditAddr => carbon_credit_addr
        getBufferPoolAddr => buffer_pool_addr
        getGovernanceReadAddress => governance_read_address
        getStorageVersion => storage_version
        setGovernance => set_governance
        acceptGovernance => accept_governance
        getGovernance => governance
        getPendingGovernance => pending_governance
        revokeGovernance => revoke_governance
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
