// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           12
// Async Callback (empty):               1
// Total number of exported functions:  15

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    drwa_identity_registry
    (
        init => init
        upgrade => upgrade
        registerIdentity => register_identity
        updateComplianceStatus => update_compliance_status
        deactivateIdentity => deactivate_identity
        eraseIdentity => erase_identity
        getIdentity => identity
        setValidityConfig => set_validity_config
        getStorageVersion => storage_version
        setGovernance => set_governance
        acceptGovernance => accept_governance
        revokeGovernance => revoke_governance
        getGovernance => governance
        getPendingGovernance => pending_governance
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
