// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           43
// Async Callback (empty):               1
// Total number of exported functions:  46

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    mrv_registry
    (
        init => init
        upgrade => upgrade
        registerMethodology => register_methodology
        setMethodologyApprovalStatus => set_methodology_approval_status
        supersedeMethodology => supersede_methodology
        registerProject => register_project
        setProjectStatus => set_project_status
        registerEvidence => register_evidence
        createVerificationCase => create_verification_case
        updateVerificationCase => update_verification_case
        createIssuanceLot => create_issuance_lot
        retireIssuanceLot => retire_issuance_lot
        reverseIssuanceLot => reverse_issuance_lot
        anchorReportV2 => anchor_report_v2
        amendReportV2 => amend_report_v2
        getReportProof => get_report_proof
        getReportProofBySeason => get_report_proof_by_season
        getReportIdBySeason => get_report_id_by_season
        isReportAnchored => is_report_anchored
        getAnchoredReportsCount => get_anchored_reports_count
        getMethodologyRecord => get_methodology_record
        getMethodologyRecordsCount => get_methodology_records_count
        getProjectRecord => get_project_record
        getProjectRecordsCount => get_project_records_count
        getEvidenceRecord => get_evidence_record
        getEvidenceRecordsCount => get_evidence_records_count
        getVerificationCase => get_verification_case
        getVerificationCasesCount => get_verification_cases_count
        getIssuanceLot => get_issuance_lot
        getIssuanceLotsCount => get_issuance_lots_count
        registerAccreditedVvb => register_accredited_vvb
        deregisterAccreditedVvb => deregister_accredited_vvb
        isVvbAccredited => is_vvb_accredited
        commitExecutionBundle => commit_execution_bundle
        submitVerificationStatement => submit_verification_statement
        submitVerifierAdjustment => submit_verifier_adjustment
        getExecutionBundle => get_execution_bundle
        getVerificationStatement => get_verification_statement
        getVerificationCaseVersion => verification_case_version
        getStorageVersion => storage_version
        setGovernance => set_governance
        acceptGovernance => accept_governance
        getGovernance => governance
        getPendingGovernance => pending_governance
        revokeGovernance => revoke_governance
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
