// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct CarbonCreditProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for CarbonCreditProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = CarbonCreditProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        CarbonCreditProxyMethods { wrapped_tx: tx }
    }
}

pub struct CarbonCreditProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, To, Gas> CarbonCreditProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn get_dvcu_token_id(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, TokenIdentifier<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getDvcuTokenId")
            .original_result()
    }

    pub fn get_dgsc_token_id(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, TokenIdentifier<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getDgscTokenId")
            .original_result()
    }

    pub fn get_total_dvcu_minted(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getTotalDvcuMinted")
            .original_result()
    }

    pub fn get_total_dvcu_burned(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getTotalDvcuBurned")
            .original_result()
    }

    pub fn get_total_dgsc_minted(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getTotalDgscMinted")
            .original_result()
    }

    pub fn get_total_dgsc_burned(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getTotalDgscBurned")
            .original_result()
    }

    pub fn get_gsoc_project_total_issued<Arg0: ProxyArg<ManagedBuffer<Env::Api>>>(
        self,
        project_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getGsocProjectTotalIssued")
            .argument(&project_id)
            .original_result()
    }

    pub fn get_gsoc_project_total_retired<Arg0: ProxyArg<ManagedBuffer<Env::Api>>>(
        self,
        project_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getGsocProjectTotalRetired")
            .argument(&project_id)
            .original_result()
    }

    pub fn get_gsoc_project_serial_count<Arg0: ProxyArg<ManagedBuffer<Env::Api>>>(
        self,
        project_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u64> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getGsocProjectSerialCount")
            .argument(&project_id)
            .original_result()
    }

    pub fn get_canonical_gsoc_serial_inventory_hash<Arg0: ProxyArg<ManagedBuffer<Env::Api>>>(
        self,
        project_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedBuffer<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getCanonicalGsocSerialInventoryHash")
            .argument(&project_id)
            .original_result()
    }
}
