// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;
use crate::{ReserveProof, GsocReserveProof};

pub struct ReserveProofRegistryProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for ReserveProofRegistryProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = ReserveProofRegistryProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        ReserveProofRegistryProxyMethods { wrapped_tx: tx }
    }
}

pub struct ReserveProofRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> ReserveProofRegistryProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        governance: Arg0,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .argument(&governance)
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> ReserveProofRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }

    pub fn anchor_reserve_proof<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<BigUint<Env::Api>>,
        Arg2: ProxyArg<BigUint<Env::Api>>,
        Arg3: ProxyArg<BigUint<Env::Api>>,
        Arg4: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg5: ProxyArg<u64>,
    >(
        self,
        token_id: Arg0,
        total_supply_scaled: Arg1,
        total_buffer_scaled: Arg2,
        total_retired_scaled: Arg3,
        merkle_root: Arg4,
        snapshot_block: Arg5,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("anchorReserveProof")
            .argument(&token_id)
            .argument(&total_supply_scaled)
            .argument(&total_buffer_scaled)
            .argument(&total_retired_scaled)
            .argument(&merkle_root)
            .argument(&snapshot_block)
            .original_result()
    }

    pub fn anchor_gsoc_reserve_proof<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<u64>,
        Arg2: ProxyArg<u64>,
        Arg3: ProxyArg<u64>,
        Arg4: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg5: ProxyArg<u64>,
    >(
        self,
        project_id: Arg0,
        total_issued: Arg1,
        total_retired: Arg2,
        serial_count: Arg3,
        itmo_serial_hash: Arg4,
        snapshot_block: Arg5,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("anchorGsocReserveProof")
            .argument(&project_id)
            .argument(&total_issued)
            .argument(&total_retired)
            .argument(&serial_count)
            .argument(&itmo_serial_hash)
            .argument(&snapshot_block)
            .original_result()
    }

    pub fn get_reserve_proof<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<u64>,
    >(
        self,
        token_id: Arg0,
        snapshot_block: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, OptionalValue<ReserveProof<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getReserveProof")
            .argument(&token_id)
            .argument(&snapshot_block)
            .original_result()
    }

    pub fn get_latest_reserve_proof<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        token_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, OptionalValue<ReserveProof<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getLatestReserveProof")
            .argument(&token_id)
            .original_result()
    }

    pub fn get_gsoc_reserve_proof<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<u64>,
    >(
        self,
        project_id: Arg0,
        snapshot_block: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, OptionalValue<GsocReserveProof<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getGsocReserveProof")
            .argument(&project_id)
            .argument(&snapshot_block)
            .original_result()
    }

    pub fn get_latest_gsoc_reserve_proof<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        project_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, OptionalValue<GsocReserveProof<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getLatestGsocReserveProof")
            .argument(&project_id)
            .original_result()
    }

    pub fn set_governance<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        governance: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setGovernance")
            .argument(&governance)
            .original_result()
    }

    pub fn accept_governance(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("acceptGovernance")
            .original_result()
    }

    pub fn governance(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedAddress<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getGovernance")
            .original_result()
    }

    pub fn pending_governance(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedAddress<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getPendingGovernance")
            .original_result()
    }
}
