// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           14
// Async Callback (empty):               1
// Total number of exported functions:  17

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    drwa_policy_registry
    (
        init => init
        upgrade => upgrade
        setTokenPolicy => set_token_policy
        deactivateTokenPolicy => deactivate_token_policy
        getTokenPolicy => token_policy
        getTokenPolicyVersion => token_policy_version
        setWhitePaperCid => set_white_paper_cid
        setRegistrationStatus => set_registration_status
        getWhitePaperCid => get_white_paper_cid
        getRegistrationStatus => get_registration_status
        getStorageVersion => storage_version
        setGovernance => set_governance
        acceptGovernance => accept_governance
        revokeGovernance => revoke_governance
        getGovernance => governance
        getPendingGovernance => pending_governance
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
