// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           20
// Async Callback (empty):               1
// Total number of exported functions:  23

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    mrv_gsoc_registry
    (
        init => init
        upgrade => upgrade
        reserveSerial => reserve_serial
        registerSerialBatch => register_serial_batch
        cancelReservation => cancel_reservation
        recordRetirement => record_retirement
        getSerialRecord => get_serial_record
        getTotalSupply => get_total_supply
        getTotalRetired => get_total_retired
        isSerialRetired => is_serial_retired
        getRetirementRecord => get_retirement_record
        getProjectSerialCount => get_project_serials
        isSerialReserved => is_serial_reserved
        addVerifier => add_verifier
        removeVerifier => remove_verifier
        isVerifier => is_verifier
        getStorageVersion => storage_version
        setGovernance => set_governance
        acceptGovernance => accept_governance
        getGovernance => governance
        getPendingGovernance => pending_governance
        revokeGovernance => revoke_governance
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
