// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           23
// Async Callback (empty):               1
// Total number of exported functions:  26

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    mrv_governance
    (
        init => init
        upgrade => upgrade
        addSigner => add_signer
        removeSigner => remove_signer
        setApprovalThreshold => set_approval_threshold
        setTimelockSeconds => set_timelock_seconds
        proposeEmergencyPause => propose_emergency_pause
        proposeVerifierAccreditation => propose_verifier_accreditation
        proposeBadgeIssuance => propose_badge_issuance
        approveProposal => approve_proposal
        executeProposal => execute_proposal
        getProposal => get_proposal
        isSigner => is_signer
        getPaused => paused
        getApprovalThreshold => approval_threshold
        getTimelockSeconds => timelock_seconds
        getVerifierAccreditation => get_verifier_accreditation
        isAccreditedVvb => is_accredited_vvb
        getBadgeIssuance => get_badge_issuance
        proposeGsocVerifier => propose_gsoc_verifier
        approveGsocVerifierProposal => approve_gsoc_verifier_proposal
        executeGsocVerifierProposal => execute_gsoc_verifier_proposal
        removeGsocVerifier => remove_gsoc_verifier
        isGsocVerifierApproved => is_gsoc_verifier_approved
        getStorageVersion => storage_version
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
