// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           13
// Async Callback (empty):               1
// Total number of exported functions:  16

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    drwa_asset_manager
    (
        init => init
        upgrade => upgrade
        registerAsset => register_asset
        syncHolderCompliance => sync_holder_compliance
        updateAsset => update_asset
        initiateWindDown => initiate_wind_down
        isWindDownInitiated => is_wind_down_initiated
        getAsset => asset
        getHolderMirror => get_holder_mirror
        getStorageVersion => storage_version
        setGovernance => set_governance
        acceptGovernance => accept_governance
        revokeGovernance => revoke_governance
        getGovernance => governance
        getPendingGovernance => pending_governance
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
