// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           11
// Async Callback (empty):               1
// Total number of exported functions:  14

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    drwa_common_test_harness
    (
        init => init
        upgrade => upgrade
        validateTokenId => validate_token_id
        validateKycStatus => validate_kyc_status
        validateAmlStatus => validate_aml_status
        testPushLenPrefixed => test_push_len_prefixed
        testSerializeSyncPayload => test_serialize_sync_payload
        testEmitMaxSyncEnvelope => test_emit_max_sync_envelope
        setGovernance => set_governance
        acceptGovernance => accept_governance
        revokeGovernance => revoke_governance
        getGovernance => governance
        getPendingGovernance => pending_governance
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
