// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            8
// Async Callback (empty):               1
// Total number of exported functions:  11

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    drwa_attestation
    (
        init => init
        upgrade => upgrade
        setAuditor => set_auditor
        acceptAuditor => accept_auditor
        revokeAuditor => revoke_auditor
        recordAttestation => record_attestation
        revokeAttestation => revoke_attestation
        getAttestation => attestation
        getAuditor => auditor
        getStorageVersion => storage_version
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
