// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           11
// Async Callback (empty):               1
// Total number of exported functions:  14

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    mrv_governance_multisig
    (
        init => init
        upgrade => upgrade
        addSigner => add_signer
        removeSigner => remove_signer
        proposeAction => propose_action
        approveProposal => approve_proposal
        executeProposal => execute_proposal
        submitDispute => submit_dispute
        voteOnDispute => vote_on_dispute
        getProposal => get_proposal
        getDispute => get_dispute
        isSigner => is_signer
        getStorageVersion => storage_version
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
