// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;
use drwa_common::DrwaSyncEnvelope;
use crate::IdentityRecord;

pub struct DrwaIdentityRegistryProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for DrwaIdentityRegistryProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = DrwaIdentityRegistryProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        DrwaIdentityRegistryProxyMethods { wrapped_tx: tx }
    }
}

pub struct DrwaIdentityRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> DrwaIdentityRegistryProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        governance: Arg0,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .argument(&governance)
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> DrwaIdentityRegistryProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }

    pub fn register_identity<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg3: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg4: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        subject: Arg0,
        legal_name: Arg1,
        jurisdiction_code: Arg2,
        registration_number: Arg3,
        entity_type: Arg4,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, DrwaSyncEnvelope<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("registerIdentity")
            .argument(&subject)
            .argument(&legal_name)
            .argument(&jurisdiction_code)
            .argument(&registration_number)
            .argument(&entity_type)
            .original_result()
    }

    pub fn update_compliance_status<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg3: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg4: ProxyArg<u64>,
    >(
        self,
        subject: Arg0,
        kyc_status: Arg1,
        aml_status: Arg2,
        investor_class: Arg3,
        expiry_round: Arg4,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, DrwaSyncEnvelope<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("updateComplianceStatus")
            .argument(&subject)
            .argument(&kyc_status)
            .argument(&aml_status)
            .argument(&investor_class)
            .argument(&expiry_round)
            .original_result()
    }

    pub fn deactivate_identity<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        subject: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, DrwaSyncEnvelope<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("deactivateIdentity")
            .argument(&subject)
            .original_result()
    }

    pub fn identity<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        subject: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, IdentityRecord<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getIdentity")
            .argument(&subject)
            .original_result()
    }

    pub fn set_governance<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        governance: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setGovernance")
            .argument(&governance)
            .original_result()
    }

    pub fn accept_governance(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("acceptGovernance")
            .original_result()
    }

    pub fn revoke_governance(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("revokeGovernance")
            .original_result()
    }

    pub fn governance(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedAddress<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getGovernance")
            .original_result()
    }

    pub fn pending_governance(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedAddress<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getPendingGovernance")
            .original_result()
    }
}
