// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;
use drwa_common::DrwaSyncEnvelope;
use crate::AttestationRecord;

pub struct DrwaAttestationProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for DrwaAttestationProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = DrwaAttestationProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        DrwaAttestationProxyMethods { wrapped_tx: tx }
    }
}

pub struct DrwaAttestationProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> DrwaAttestationProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        auditor: Arg0,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .argument(&auditor)
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> DrwaAttestationProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }

    pub fn set_auditor<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        auditor: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setAuditor")
            .argument(&auditor)
            .original_result()
    }

    pub fn accept_auditor(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("acceptAuditor")
            .original_result()
    }

    pub fn record_attestation<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedAddress<Env::Api>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg3: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg4: ProxyArg<bool>,
    >(
        self,
        token_id: Arg0,
        subject: Arg1,
        attestation_type: Arg2,
        evidence_hash: Arg3,
        approved: Arg4,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, DrwaSyncEnvelope<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("recordAttestation")
            .argument(&token_id)
            .argument(&subject)
            .argument(&attestation_type)
            .argument(&evidence_hash)
            .argument(&approved)
            .original_result()
    }

    pub fn revoke_attestation<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        token_id: Arg0,
        subject: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, DrwaSyncEnvelope<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("revokeAttestation")
            .argument(&token_id)
            .argument(&subject)
            .original_result()
    }

    pub fn attestation<
        Arg0: ProxyArg<ManagedBuffer<Env::Api>>,
        Arg1: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        token_id: Arg0,
        subject: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, AttestationRecord<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getAttestation")
            .argument(&token_id)
            .argument(&subject)
            .original_result()
    }

    pub fn auditor(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedAddress<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getAuditor")
            .original_result()
    }
}
