// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            8
// Async Callback (empty):               1
// Total number of exported functions:  11

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    mrv_atomic_swap
    (
        init => init
        upgrade => upgrade
        createRfq => create_rfq
        depositMargin => deposit_margin
        settle => settle
        autoReclaim => auto_reclaim
        cancelRfq => cancel_rfq
        getRfq => get_rfq
        getLockedBalance => get_locked_balance
        getStorageVersion => storage_version
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
